version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
